CREATE TABLE outbox_eventos (
    id UUID PRIMARY KEY,
    tipo_evento VARCHAR(100) NOT NULL,
    agregado VARCHAR(100) NOT NULL,
    agregado_id VARCHAR(100) NOT NULL,
    payload CLOB NOT NULL,
    correlation_id VARCHAR(100) NOT NULL,
    publicado BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    CONSTRAINT uk_curso_codigo UNIQUE (codigo)
);

CREATE TABLE alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    matricula VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_aluno_email UNIQUE (email),
    CONSTRAINT uk_aluno_matricula UNIQUE (matricula)
);

CREATE TABLE disciplinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    curso_id BIGINT NOT NULL,
    CONSTRAINT uk_disciplina_codigo UNIQUE (codigo),
    CONSTRAINT fk_disciplina_curso FOREIGN KEY (curso_id) REFERENCES cursos (id)
);

CREATE TABLE turmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    disciplina_id BIGINT NOT NULL,
    capacidade INTEGER NOT NULL CHECK (capacidade > 0),
    vagas_disponiveis INTEGER NOT NULL CHECK (vagas_disponiveis >= 0),
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_turma_codigo UNIQUE (codigo),
    CONSTRAINT fk_turma_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id),
    CONSTRAINT ck_turma_status CHECK (status IN ('ABERTA', 'FECHADA')),
    CONSTRAINT ck_turma_vagas_capacidade CHECK (vagas_disponiveis <= capacidade)
);

CREATE TABLE matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    turma_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    criada_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmada_em TIMESTAMP WITH TIME ZONE NULL,
    cancelada_em TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id),
    CONSTRAINT fk_matricula_turma FOREIGN KEY (turma_id) REFERENCES turmas (id),
    CONSTRAINT uk_matricula_aluno_turma UNIQUE (aluno_id, turma_id),
    CONSTRAINT ck_matricula_status CHECK (status IN ('PENDENTE', 'CONFIRMADA', 'CANCELADA'))
);

CREATE INDEX idx_matriculas_aluno_id ON matriculas (aluno_id);
CREATE INDEX idx_matriculas_turma_id ON matriculas (turma_id);
